collections:
  dms:
    output: true
  games:
    output: true
  systems:
    output: true
  players:
    output: true
  NPCs:
    output: true
  locations:
    output: true
  quests:
    output: true

defaults:
  - scope:
      path: ""
      type: "dms"
    values:
      layout: "dm"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
name: Angeleah Hoeppner
markdown: kramdown
